source "https://rubygems.org"

gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
end

# Required on Ruby 3.x
gem "webrick", "~> 1.8"
gem "csv"
gem "base64"
gem "bigdecimal"
